AWSTemplateFormatVersion: 2010-09-09
Description: Deploy list-account-in-organizations lambda.

Parameters:
  FunctionName:
    Type: String
    Default: list-account-in-organizations

  ListAccountsRoleName:
    Type: String
    Default: role_list_accounts

  PaymentAccountId:
    Type: String
    Default: xxxxxxxxxxxx

Resources:

  AssumeOrgRootPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: "policy_assume_org_root"
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: "PermissionToAssumeRole"
          Effect: Allow
          Action:
          - "sts:AssumeRole"
          Resource:
          - !Sub arn:aws:iam::*:role/${ListAccountsRoleName}

  AssumeOrgRootRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "role_assume_org_root"
      Path: "/"
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSLambdaExecute
      - !Ref AssumeOrgRootPolicy
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole

  ListAccountLambda:
    Type: AWS::Lambda::Function
    Properties:
      Code: lambda/
      FunctionName: !Ref FunctionName
      Environment:
        Variables:
          ASSUME_ROLE_NAME: !Sub ${ListAccountsRoleName}
          PAYMENT_ACCOUNT_ID: !Sub ${PaymentAccountId}
      Handler: main.handler
      Role: !GetAtt AssumeOrgRootRole.Arn
      Runtime: python3.12
      Timeout: 60
